let allMusic = [
  {
    name: "Wave to Earth - Seasons",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Harry Styles - From the Dining Table",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Djo - End of Beginning",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Billie Eilish - Birds of a Feather",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Lana Del Rey - Cinnamon Girl",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Lord Huron - The Night We Met",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Scot Street - Phoebe Bridgers",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Boyz II Men - On Bended Knee",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Bruno Mars - When I Was Your Man",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Wave to Earth - Seasons",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Wave to Earth - Seasons",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Wave to Earth - Seasons",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Wave to Earth - Seasons",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Wave to Earth - Seasons",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
  {
    name: "Wave to Earth - Seasons",
    artist: "Seasons",
    img: "music",
    src: "music1",
  },
];
